class EventTypes:
    BATTERY_CHARGE = "battery_charge"
    GAME_FLOW_FINISH_INTRO = "game_flow_finish_intro"
    GAME_FLOW_FINISH_TUTORIAL = "game_flow_finish_tutorial"
    GAME_FLOW_JUMP = "game_flow_jump"
    RETRIEVE_PLANET_DATA = "retrieve_planet_data"
    RETRIEVE_SHIP_STATUS = "retrieve_ship_status"
    RETRIEVE_SYSTEM_UPGRADES = "retrieve_system_upgrades"
    RETRIEVE_SYSTEM_WINDOW_DATA = "retrieve_system_window_data"
    SHIP_RETRIEVE_SYSTEM = "ship_retrieve_system"
    SHIP_DAMAGE_SYSTEM = "ship_damage_system"
    UI_CLOSE_SYSTEM_WINDOW = "ui_close_system_window"
    UI_OPEN_SYSTEM_WINDOW = "ui_open_system_window"
    UI_START_PLANET_VIEW_EMERGENCY = "ui_start_planet_view_emergency"
    UI_STOP_PLANET_VIEW_EMERGENCY = "ui_stop_planet_view_emergency"