class ResponseTypes:
    AMOUNT_MATTER = "amount_matter"
    BATTERY_DRAWN_ENERGY_LOG = "battery_drawn_energy_log"
    DIALOGUE_EVENT_RESPONSE = "dialogue_event_response"
    PLANET_DATA = "planet_data"
    SCANNER_RESULT = "scanner_result"
    SHIP_DATA = "ship_data"
    SHIP_STATUS_LOG = "ship_status_log"
    SHIP_STATUS_LOG_ENTRY = "ship_status_log_entry"
    SYSTEM_UPGRADES = "system_upgrades"
    SYSTEM_WINDOW_DATA = "system_window_data"
    UPGRADE_COST = "upgrade_cost"